language: php
php:
  - "5.6"
  - "7.0"

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
